[workspace]
members = [
    "castella-skia-core",
    "bindings/python",
]
exclude = [
    "pydantic-core-ios-build",
]
resolver = "2"

[workspace.package]
version = "0.1.2"
edition = "2021"
license = "MIT"
repository = "https://github.com/i2y/castella"
authors = ["Yasushi Itoh <i2y@icloud.com>"]
